name: MockAPI Tests
on: [push] # Run on each code update

jobs:
  run-newman:
    runs-on: ubuntu-latest
    steps:
      # 1. Upload files from the repository in the GitHub cloud
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Install Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install Newman
      - name: Install Newman
        run: npm install -g newman

      # 4. Run tests
      - name: Run Tests
        run: newman run mockapi.io.postman_collection.json -e mockapi.io.postman_environment.json --env-var "mokeapi_url=${{ secrets.API_BASE_URL }}" --reporters cli
